# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DesignPatternsArchitectures' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DesignPatternsArchitectures
   pod 'KVOController'
   pod 'ReactiveObjC'
end
